#!/bin/sh

_PATH=`pwd`
echo _PATH: $_PATH


updateCoreScript(){
	sudo cp $_PATH/core /usr/bin/
	
	sudo cp $_PATH/data/coreStartup.service /etc/systemd/system/coreStartup.service
	sudo chmod 664 /etc/systemd/system/coreStartup.service
	sudo systemctl daemon-reload
	sudo systemctl enable coreStartup.service

	echo "updateCoreScript: core command & service updated!\n"
	# sudo chmod +x "$_PATH"/core.sh
}

exitIfNoArgs(){
	if [ $# -eq 0 ]
	then
		echo "No arguments supplied, exiting."
		exit 0
	fi
}

ifStop(){
	if [ $1 = "stop" ]; then
		sudo killall node
		echo "\nCORE STOPPED."
		exit 0
	fi
}

ifReset(){
	if [ $1 = "reset" ]; then
		echo "\nCORE RESETED !"
		sudo rm -r -f $_PATH/tmp
		exit 0
	fi
}

ifCerbot(){
	if [ $1 = "certbot" ]; then
		echo "\nCERTBOT..."
		sudo sh $_PATH/src/shell/certbot.sh
		exit 0
	fi
}


updateCoreScript $*

exitIfNoArgs $*

ifStop $*

ifReset $*

ifCerbot $*

clear

 _NAME=$1


# Test if log directory exists
if [ ! -d "$_PATH"/log ];
then
	mkdir "$_PATH"/log
	echo "log directory created"
fi

echo "\nStarting Wrapper... [$*]" | sudo tee -a "$_PATH/log/$_NAME.log"

# sudo python /home/odi/core/src/python/buttons.py 2>&1 | sudo tee -a /home/odi/core/log/buttons.py.log &
sudo node "$_PATH"/src/wrapper.js $* 2>&1 | sudo tee -a "$_PATH/log/$_NAME.log" &
