#!/bin/sh


setupCoreCommandAndService(){
	sudo cp /home/odi/core/core /usr/bin/
	
	sudo cp /home/odi/core/data/coreStartup.service /etc/systemd/system/coreStartup.service
	sudo chmod 664 /etc/systemd/system/coreStartup.service
	sudo systemctl daemon-reload
	sudo systemctl enable coreStartup.service

	echo "setupCoreCommand: core command & service updated!\n"
	# sudo chmod +x "$_PATH"/core.sh
}

exitIfNoArgs(){
	if [ $# -eq 0 ]
	then
		echo "No arguments supplied, exiting."
		exit 0
	fi
}

ifStop(){
	if [ $1 = "stop" ]; then
		sudo killall node
		echo "\nCORE STOPPED."
		exit 0
	fi
}

ifReset(){
	if [ $1 = "reset" ]; then
		echo "\nCORE RESETED !"
		sudo rm -r -f /home/odi/core/tmp
		exit 0
	fi
}

ifCerbot(){
	if [ $1 = "cerbot" ]; then
		echo "\nCERBOT..."
		sh /home/odi/core/src/shell/cerbot.sh
		exit 0
	fi
}


setupCoreCommandAndService $*

exitIfNoArgs $*

ifStop $*

ifReset $*

ifCerbot $*

clear

 _NAME=$1
 
#_PATH=`pwd`
_PATH="/home/odi/core/"
echo _PATH $_PATH

# Test if log directory exists
if [ ! -d "$_PATH"/log ];
then
	mkdir "$_PATH"/log
	echo "log directory created"
fi

echo "\nStarting Wrapper... [$*]" | sudo tee -a "$_PATH/log/$_NAME.log"

# sudo python /home/odi/core/src/python/buttons.py 2>&1 | sudo tee -a /home/odi/core/log/odi.log &
# sudo python /home/odi/core/src/python/buttons.py 2>&1 | sudo tee -a /home/odi/core/log/buttons.py.log &
sudo node "$_PATH"/src/wrapper.js $* 2>&1 | sudo tee -a "$_PATH/log/$_NAME.log" &
