#!/bin/sh

_PATH=`pwd`
echo _PATH: $_PATH


updateFrameBotScript(){
	sudo cp $_PATH/frameBot /usr/bin/
	
	sudo cp $_PATH/data/frameBot.service /etc/systemd/system/frameBot.service
	sudo chmod 744 /etc/systemd/system/frameBot.service
	sudo systemctl daemon-reload
	sudo systemctl enable frameBot.service
	sudo systemctl start frameBot.service

	echo "frameBot: frameBot command & service updated!\n"
	# sudo chmod +x "$_PATH"/frameBot.sh
}

exitIfNoArgs(){
	if [ $# -eq 0 ]
	then
		echo "No arguments supplied, exiting."
		exit 0
	fi
}

ifStop(){
	if [ $1 = "stop" ]; then
		sudo killall node
		echo "\nframeBot STOPPED."
		exit 0
	fi
}

ifReset(){
	if [ $1 = "reset" ]; then
		echo "\nframeBot RESETED !"
		sudo rm -r -f $_PATH/tmp
		exit 0
	fi
}

ifCerbot(){
	if [ $1 = "certbot" ]; then
		echo "\nCERTBOT..."
		sudo sh $_PATH/src/shell/certbot.sh
		exit 0
	fi
}


updateFrameBotScript $*

exitIfNoArgs $*

ifStop $*

ifReset $*

ifCerbot $*

clear

 _NAME=$1


# Test if log directory exists
if [ ! -d "$_PATH"/log ];
then
	mkdir "$_PATH"/log
	echo "log directory created"
fi

echo "\nStarting Wrapper... [$*]" | sudo tee -a "$_PATH/log/$_NAME.log"

# sudo python /home/odi/frameBot/src/python/buttons.py 2>&1 | sudo tee -a /home/odi/frameBot/log/buttons.py.log &
sudo node "$_PATH"/src/wrapper.js $* 2>&1 | sudo tee -a "$_PATH/log/$_NAME.log" &
