#!/bin/sh

_PATH=`pwd`
echo _PATH: $_PATH


updateFrameBotScript(){
	sudo cp $_PATH/framebot /bin/ && \
	
	sudo cp $_PATH/data/framebot.service /etc/systemd/system && \
	sudo chmod 744 /etc/systemd/system/framebot.service && \
	sudo systemctl daemon-reload && \
	sudo systemctl enable framebot.service && \
	sudo systemctl start framebot.service

	echo "framebot: framebot command & service updated!\n"
	# sudo chmod +x "$_PATH"/framebot.sh
}

exitIfNoArgs(){
	if [ $# -eq 0 ]
	then
		echo "No arguments supplied, exiting."
		exit 0
	fi
}

ifStop(){
	if [ $1 = "stop" ]; then
		#sudo service framebot stop
		sudo killall node
		echo "\nframebot STOPPED."
		exit 0
	fi
}

ifLogtail(){
	if [ $1 = "log" ]; then
	tail -f /log/odi.log
	fi
	exit 0
}

ifReset(){
	if [ $1 = "reset" ]; then
		echo "\nframebot RESETED !"
		sudo rm -r -f $_PATH/tmp
		exit 0
	fi
}

ifCerbot(){
	if [ $1 = "certbot" ]; then
		echo "\nCERTBOT..."
		sudo sh $_PATH/src/shell/certbot.sh
		exit 0
	fi
}


updateFrameBotScript

exitIfNoArgs $*

ifStop $*

ifLogtail $*

ifReset $*

ifCerbot $*

clear

_NAME=$1

# Create log directory if not exists
if [ ! -d "$_PATH"/log ];
then
	mkdir "$_PATH"/log
	echo "log directory created"
fi

echo "\nStarting Wrapper... [$*]" | sudo tee -a "$_PATH/log/$_NAME.log"

# sudo python /home/odi/framebot/src/python/buttons.py 2>&1 | sudo tee -a /home/odi/framebot/log/buttons.py.log &
sudo node "$_PATH"/src/wrapper.js $* 2>&1 | sudo tee -a "$_PATH/log/$_NAME.log" 
